
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import {Sidebar, SidebarContent, SidebarHeader, SidebarMenu, SidebarMenuItem, SidebarProvider, SidebarTrigger, SidebarSeparator, SidebarGroup, SidebarGroupLabel, SidebarGroupContent, SidebarMenuButton, SidebarFooter, SidebarInset} from "@/components/ui/sidebar";
import { Button } from '@/components/ui/button';
import { Icons } from '@/components/icons';
import Link from 'next/link';
import { Input } from '@/components/ui/input';
import React from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Cybersecurity Portfolio',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <Sidebar collapsible="icon">
            <SidebarHeader>
              <Link href="#" className="flex items-center space-x-2">
                <Icons.shield className="h-6 w-6 text-green-500" aria-hidden="true" />
                <span className="font-bold">CyberSecurity Portfolio</span>
              </Link>
              <SidebarSeparator />
            </SidebarHeader>
            <SidebarContent>
              <SidebarGroup>
                <SidebarGroupLabel>NAVIGATION</SidebarGroupLabel>
                <SidebarMenu>
                  <SidebarMenuItem>
                    <SidebarMenuButton asChild>
                      <Link href="/">
                        <Icons.home className="mr-2 h-4 w-4" aria-hidden="true" />
                        <span>Home</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                  <SidebarMenuItem>
                    <SidebarMenuButton asChild>
                      <Link href="/about">
                        <Icons.user className="mr-2 h-4 w-4" aria-hidden="true" />
                        <span>About</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                  <SidebarMenuItem>
                    <SidebarMenuButton asChild>
                      <Link href="/projects">
                        <Icons.workflow className="mr-2 h-4 w-4" aria-hidden="true" />
                        <span>Projects</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                  <SidebarMenuItem>
                    <SidebarMenuButton asChild>
                      <Link href="/contact">
                        <Icons.mail className="mr-2 h-4 w-4" aria-hidden="true" />
                        <span>Contact</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                </SidebarMenu>
              </SidebarGroup>
            </SidebarContent>
            <SidebarFooter>
              <SidebarSeparator />
              <p className="text-xs text-muted-foreground px-2">
                &copy; {new Date().getFullYear()} Thomas Shelby. All rights reserved.
              </p>
            </SidebarFooter>
          </Sidebar>
          <SidebarInset>
            <header className="sticky top-0 z-40 border-b bg-background">
              <div className="container flex h-16 items-center justify-between">
                <div className="flex items-center space-x-4">
                  <SidebarTrigger className="lg:hidden" />
                  <Link href="#" className="hidden items-center space-x-2 md:flex">
                    <Icons.shield className="h-6 w-6 text-green-500" aria-hidden="true" />
                    <span className="font-bold">CyberSecurity Portfolio</span>
                  </Link>
                  <div className="relative">
                    <Input type="search" placeholder="Search..." className="md:w-[300px]" />
                    <Icons.search className="absolute right-2.5 top-3 h-4 w-4 text-muted-foreground" aria-hidden="true" />
                  </div>
                </div>
                <nav className="flex items-center space-x-2">
                  <Button variant="ghost" size="sm">
                    <Icons.github className="mr-2 h-4 w-4" aria-hidden="true" />
                    GitHub
                  </Button>
                  <Button variant="ghost" size="sm">
                    <Icons.linkedin className="mr-2 h-4 w-4" aria-hidden="true" />
                    LinkedIn
                  </Button>
                </nav>
              </div>
            </header>
            <main className="flex-1">
              <div className="container py-12">
                {children}
              </div>
            </main>
          </SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
